import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import QueryProvider from "@/components/QueryProvider";
const shabnam = localFont({
  src: [
    {
      path: "./fonts/Shabnam.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Shabnam-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-shabnam",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={cn(shabnam.variable, "min-h-screen antialiased")}
        style={{
          fontFamily: "var(--font-shabnam), var(--font-geist-sans), var(--font-geist-mono), Arial, sans-serif",
        }}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
